// Auto-generated by `pnpm db:types`. Do not edit manually.
// Run `pnpm db:types` after schema changes to regenerate.
// Last manual update: Phase 1 Step 1.1 — core schema added.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      _audit_log: {
        Row: {
          action: string;
          created_at: string;
          id: string;
          new_data: Json | null;
          old_data: Json | null;
          record_id: string | null;
          table_name: string;
          tenant_id: string | null;
          user_id: string | null;
        };
        Insert: {
          action: string;
          created_at?: string;
          id?: string;
          new_data?: Json | null;
          old_data?: Json | null;
          record_id?: string | null;
          table_name: string;
          tenant_id?: string | null;
          user_id?: string | null;
        };
        Update: {
          action?: string;
          created_at?: string;
          id?: string;
          new_data?: Json | null;
          old_data?: Json | null;
          record_id?: string | null;
          table_name?: string;
          tenant_id?: string | null;
          user_id?: string | null;
        };
        Relationships: [];
      };
      ingredients: {
        Row: {
          active: boolean;
          cost_per_unit_cents: number;
          created_at: string;
          id: string;
          name_en: string | null;
          name_he: string;
          pkg_qty: number | null;
          tenant_id: string;
          unit: string;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          cost_per_unit_cents?: number;
          created_at?: string;
          id?: string;
          name_en?: string | null;
          name_he: string;
          pkg_qty?: number | null;
          tenant_id: string;
          unit: string;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          cost_per_unit_cents?: number;
          created_at?: string;
          id?: string;
          name_en?: string | null;
          name_he?: string;
          pkg_qty?: number | null;
          tenant_id?: string;
          unit?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ingredients_tenant_id_fkey';
            columns: ['tenant_id'];
            isOneToOne: false;
            referencedRelation: 'tenants';
            referencedColumns: ['id'];
          },
        ];
      };
      memberships: {
        Row: {
          created_at: string;
          id: string;
          role: string;
          tenant_id: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          role: string;
          tenant_id: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          role?: string;
          tenant_id?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'memberships_tenant_id_fkey';
            columns: ['tenant_id'];
            isOneToOne: false;
            referencedRelation: 'tenants';
            referencedColumns: ['id'];
          },
        ];
      };
      menu_items: {
        Row: {
          active: boolean;
          category: string;
          created_at: string;
          id: string;
          name_en: string | null;
          name_he: string;
          pos_external_id: string | null;
          price_cents: number;
          tenant_id: string;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          category: string;
          created_at?: string;
          id?: string;
          name_en?: string | null;
          name_he: string;
          pos_external_id?: string | null;
          price_cents: number;
          tenant_id: string;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          category?: string;
          created_at?: string;
          id?: string;
          name_en?: string | null;
          name_he?: string;
          pos_external_id?: string | null;
          price_cents?: number;
          tenant_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'menu_items_tenant_id_fkey';
            columns: ['tenant_id'];
            isOneToOne: false;
            referencedRelation: 'tenants';
            referencedColumns: ['id'];
          },
        ];
      };
      recipe_components: {
        Row: {
          created_at: string;
          id: string;
          ingredient_id: string | null;
          qty: number;
          recipe_id: string;
          sort_order: number;
          sub_recipe_id: string | null;
          tenant_id: string;
          unit: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          ingredient_id?: string | null;
          qty: number;
          recipe_id: string;
          sort_order?: number;
          sub_recipe_id?: string | null;
          tenant_id: string;
          unit: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          ingredient_id?: string | null;
          qty?: number;
          recipe_id?: string;
          sort_order?: number;
          sub_recipe_id?: string | null;
          tenant_id?: string;
          unit?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'recipe_components_recipe_id_fkey';
            columns: ['recipe_id'];
            isOneToOne: false;
            referencedRelation: 'recipes';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'recipe_components_ingredient_id_fkey';
            columns: ['ingredient_id'];
            isOneToOne: false;
            referencedRelation: 'ingredients';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'recipe_components_sub_recipe_id_fkey';
            columns: ['sub_recipe_id'];
            isOneToOne: false;
            referencedRelation: 'recipes';
            referencedColumns: ['id'];
          },
        ];
      };
      recipes: {
        Row: {
          active: boolean;
          created_at: string;
          id: string;
          name_en: string | null;
          name_he: string;
          tenant_id: string;
          type: string;
          updated_at: string;
          yield_qty: number;
          yield_unit: string;
        };
        Insert: {
          active?: boolean;
          created_at?: string;
          id?: string;
          name_en?: string | null;
          name_he: string;
          tenant_id: string;
          type: string;
          updated_at?: string;
          yield_qty?: number;
          yield_unit?: string;
        };
        Update: {
          active?: boolean;
          created_at?: string;
          id?: string;
          name_en?: string | null;
          name_he?: string;
          tenant_id?: string;
          type?: string;
          updated_at?: string;
          yield_qty?: number;
          yield_unit?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'recipes_tenant_id_fkey';
            columns: ['tenant_id'];
            isOneToOne: false;
            referencedRelation: 'tenants';
            referencedColumns: ['id'];
          },
        ];
      };
      tenants: {
        Row: {
          created_at: string;
          id: string;
          name: string;
          slug: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          name: string;
          slug: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          name?: string;
          slug?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      user_role_in: {
        Args: { p_tenant_id: string };
        Returns: string;
      };
      user_tenant_ids: {
        Args: Record<string, never>;
        Returns: string[];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
