-- Phase 3.1: prep_tasks — daily prep list generated by Inngest cron

CREATE TABLE public.prep_tasks (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    UUID        NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  recipe_id    UUID        NOT NULL REFERENCES public.recipes(id) ON DELETE CASCADE,
  prep_date    DATE        NOT NULL,
  qty_required NUMERIC(10,3) NOT NULL CHECK (qty_required >= 0),
  qty_actual   NUMERIC(10,3)           CHECK (qty_actual >= 0),
  unit         TEXT        NOT NULL,
  status       TEXT        NOT NULL DEFAULT 'pending'
                           CHECK (status IN ('pending','in_progress','done','skipped')),
  notes        TEXT,
  assigned_to  UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  completed_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (tenant_id, recipe_id, prep_date)
);

CREATE INDEX idx_prep_tasks_tenant_date
  ON public.prep_tasks(tenant_id, prep_date);

CREATE INDEX idx_prep_tasks_status
  ON public.prep_tasks(tenant_id, prep_date, status);

-- updated_at trigger
CREATE TRIGGER prep_tasks_set_updated_at
  BEFORE UPDATE ON public.prep_tasks
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.prep_tasks ENABLE ROW LEVEL SECURITY;

-- All members can read their tenant's prep tasks
CREATE POLICY "prep_tasks_select_member"
  ON public.prep_tasks FOR SELECT
  USING (tenant_id IN (SELECT public.user_tenant_ids()));

-- Any member can create prep tasks (Inngest service role bypasses RLS)
CREATE POLICY "prep_tasks_insert_member"
  ON public.prep_tasks FOR INSERT
  WITH CHECK (tenant_id IN (SELECT public.user_tenant_ids()));

-- Any member can update status/qty_actual; qty_required update restricted to manager+
CREATE POLICY "prep_tasks_update_member"
  ON public.prep_tasks FOR UPDATE
  USING (tenant_id IN (SELECT public.user_tenant_ids()))
  WITH CHECK (tenant_id IN (SELECT public.user_tenant_ids()));

-- Only owner/manager can delete
CREATE POLICY "prep_tasks_delete_manager"
  ON public.prep_tasks FOR DELETE
  USING (public.user_role_in(tenant_id) IN ('owner', 'manager'));

-- Rollback:
-- DROP TABLE IF EXISTS public.prep_tasks;
